### ISSUE TITLE
Qlik ANalyzer V3.1.7 Failing

### ISSUE THREAD

**Issue by pasgalbarra** [qlik-oss/qlik-cloud-reload-analyzer#16]
[Reload Analyzer v3.1.7 - wip-2024-05-10T05 27 48.613Z.log](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/files/15303836/Reload.Analyzer.v3.1.7.-.wip-2024-05-10T05.27.48.613Z.log)

Attaching error log

**Comment by withdave** [comment]
Hi @pasgalbarra 

We commonly see this issue when the user making the API call isn't a tenant admin, which is a requirement to call the reloads API without specifying an appId (see [this link](https://qlik.dev/apis/rest/reloads/#%23%2Fentries%2Fv1%2Freloads-get:~:text=TenantAdmin%20users%20may%20omit%20this%20parameter%20to%20list%20all%20reload%20history%20in%20the%20tenant.)).

Can you confirm the calling user has a tenant admin role?

**Comment by pasgalbarra** [comment]
![Screenshot 2024-05-14 130558](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/assets/169752393/98819813-4ace-4e37-a63b-70f510ed5ce7)

Yes, nothing changed and the app started failing

**Comment by withdave** [comment]
Is data returned if you navigate to `https://tenant.region.qlikcloud.com/api/v1/reloads` (change tenant and region to match your tenant) after first logging into your tenant's hub?

If yes, and you're certain that the API key in the REST connection is one that was generated for your account and it hasn't been updated by another user, please open a support case as this doesn't appear to be an issue with the Reload Analyzer.

**Comment by pasgalbarra** [comment]
[reloads.json](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/files/15307832/reloads.json)

Yes I can see this data.
Do you mean open a support case with Qlik?

Thanks.

**Comment by withdave** [comment]
Closing this as not an issue with Reload Analyzer.

Removed that reload log, as it appears to be an issue with the API key.
