### ISSUE TITLE
Time Series  / Distribution visualisations 

### ISSUE THREAD

**Issue by JohnnyAzzurri** [qlik-oss/qlik-cloud-reload-analyzer#17]
## 🚀 Feature

Visualisations for time series & distributions

![image](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/assets/108471603/a946c24f-075c-4ef8-9d7d-f265f7af85f8)

![image](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/assets/108471603/b5135590-3929-4550-ac87-2b5abf228965)

![image](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/assets/108471603/c8694a79-8e5e-4b90-99cd-e7115a2023d1)

### Motivation

I added this in myself, but could probably be finessed beyond what I've built

### Additional context

Something that's useful to see , is over time, if reload times are changing significantly, or there are spikes,  the repurposed map visualisation could probably be finessed beyond my example , which shows where, when and for how long certain reloads run ( that then might show impact of reloads on other processes(

**Comment by withdave** [comment]
Thank you @JohnnyAzzurri. We've made quite a few updates in [v4.0.1](https://github.com/qlik-oss/qlik-cloud-reload-analyzer/releases/tag/v4.0.1), do you want to take a look and let us know if any of the changes add the insights you need?
